apiVersion: apps/v1
kind: Deployment
metadata:
  name: reception-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reception-frontend
  template:
    metadata:
      labels:
        app:
          reception-frontend
    spec:
      containers:
      - name: reception-frontend
        image: sebastiancharras/reception-frontend
        ports:
        - containerPort: 80
