apiVersion: apps/v1
kind: Deployment
metadata:
  name: reception-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reception-backend
  template:
    metadata:
      labels:
        app:
          reception-backend
    spec:
      containers:
      - name: reception-backend
        image: sebastiancharras/reception-backend
        ports:
        - containerPort: 80
        env:
        - name: NODE_PORT
          value: "80"
        - name: DB_URI
          value: "mongodb://reception-db:27017/"
        - name: JWT_SECRET
          value: secret
