apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reception-pvc
  labels:
    app: reception-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
