apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sirhc-pvc
  labels:
    app: sirhc-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
