apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "reception-db"
spec:
  selector:
    matchLabels:
      app: "reception-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: "reception-db"
    spec:
      containers:
        - name: "reception-db"
          image: "mongo:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 27017
              name: "reception-db"
          volumeMounts:
            - name: "reception-persistent-storage"
              mountPath: "/reception/db"
      volumes:
        - name: "reception-persistent-storage"
          persistentVolumeClaim:
            claimName: "reception-pvc"
